---
- name: dPanel standard VM setup
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: robertdebock.users
      when: (dpanel_setup_action | default('machine.create')) != 'machine.delete'
      tags:
        - user
        - setup

    - role: dpanel-init
      tags:
        - dpanel
        - agent
        - setup
