---
- name: Install PostgreSQL
  hosts: all
  become: true
  gather_facts: true
  vars:
    app_config: "{{ config | default({}) }}"

  roles:
    - role: ANXS.postgresql
      postgresql_version: "{{ dynamic.postgresql.version | default(app_config.version | default('16')) }}"
      postgresql_listen_addresses: "{{ dynamic.postgresql.listen_addresses | default(app_config.listen_addresses | default(['localhost'])) }}"
      postgresql_admin_password: "{{ dpanel_resolved_postgresql_admin_password | default(omit) }}"
      tags:
        - postgresql

