---
- name: Install Redis
  hosts: all
  become: true
  gather_facts: true
  vars:
    app_config: "{{ config | default({}) }}"

  roles:
    - role: geerlingguy.redis
      redis_port: "{{ dynamic.redis.port | default(app_config.port | default(6379)) }}"
      tags:
        - redis

